package:
  name: pta
  version: "0.0.11"

source:
  git_url: https://github.com/isaacovercast/PTA
  git_tag: master

build:
  number: 11
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - msprime
    - cython
    - numpy
    - pandas
  run:
    - python >=3.7
    - setuptools
    - ipyparallel
    - cython
    - scipy
    - nbconvert
    - joblib
    - jupyter_client
    - jupyter
    - notebook
    - pandas
    - momi
    - msprime
    - mpmath
    - cloudpickle
    - matplotlib
    - boruta_py
    - scikit-garden
    - tzlocal
    - matplotlib
    - imagemagick

  commands:
    - PTA -v

about:
  home: https://github.com/isaacovercast/PTA
  license: GPLv3
  summary: Phylogeographic Temporal Analysis
