package:
  name: pta
  version: "0.0.15"

source:
  git_url: https://github.com/isaacovercast/PTA
  git_tag: master

build:
  number: 11
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - msprime
    - numpy>=1.17
    - pandas
  run:
    - python
    - setuptools
    - ipyparallel
    - scipy>=1.9
    - nbconvert
    - joblib
    - jupyter
    - pandas
    - matplotlib
    - momi
    - msprime
    - cloudpickle
    - boruta_py
    - scikit-learn

  commands:
    - PTA -v

about:
  home: https://github.com/isaacovercast/PTA
  license: GPLv3
  summary: Phylogeographic Temporal Analysis
