name: PTA
channels:
  - conda-forge
  - bioconda
  - PTA
dependencies:
  - jupyter
  - python=3.7
  - scikit-learn
  - anaconda-client
  - scikit-garden
  - momi
  - tzlocal
  - ipyparallel
  - rpy2
  - dadi
  - simplegeneric
  - boruta_py
